書籍一覧の表示タイプを切り替えれるように
kazu51-gh/cac-library pull request #8
Opened 2023-11-17 02:48 UTC by Oni-Men

# やったこと

- グリッドビューの列数を4から６にした
- グリッドビューのときはタイトルのみを表示するように
- グリッドビューのタイトルは2行だけ表示（入りきらない分は省略）
- リストビューを追加
- リストビューでは著者やISBNが表示される
- グリッドビューでもリストビューでも本をクリックすると詳細がポップアップされる
- 書籍一覧をコンポーネント化し「さがす」タブでも同じように表示できるようにした

## グリッドビュー
![image](https://github.com/kazu51-gh/cac-library/assets/19502796/4657fdf3-c3e2-4dac-9e56-c02dbeba9a73)

## リストビュー
![image](https://github.com/kazu51-gh/cac-library/assets/19502796/d6367ef6-a6f4-4248-8350-43b025282689)

## 詳細表示
![image](https://github.com/kazu51-gh/cac-library/assets/19502796/1ce1d1b1-0ce5-4657-b5b0-5e3be5213012)

2023-11-17 12:20 UTC, kazu51-gh requested changes

2023-11-17 12:20 UTC, kazu51-gh commented on src/components/book_list_view.tsx
> +      <div className="mb-3 w-full flex flex-row-reverse  gap-x-4 cursor-pointer">
アイコン以外にカーソルを持って行ってもポインタになっている(アイコンの左側の部分)のでアイコンそれぞれのclassNameにcursor-pointerを当てるべきかと。

2023-11-17 12:20 UTC, kazu51-gh commented on src/components/book_list_view.tsx
> +              <div onClick={() => setSelectedBookIndex(index)} key={index} className="flex items-stretch cursor-pointer">
表示崩れが発生しています。
<img width="369" alt="book_view_grid" src="https://github.com/kazu51-gh/cac-library/assets/89214751/45cf6113-78c1-4c38-b278-7170a1e26b1c">
自動改行が原因だと思うので、タイトルを考え直さないといけないかもですね...

2023-11-17 12:28 UTC, kazu51-gh commented on src/components/book_list_view.tsx
> +              <div onClick={() => setSelectedBookIndex(index)} key={index} className="flex items-stretch cursor-pointer">
ウィンドウの横サイズが1280以下の時に様々なカードで表示崩れが見られるようです。

2023-11-17 12:29 UTC, Oni-Men commented on src/components/book_list_view.tsx
> +              <div onClick={() => setSelectedBookIndex(index)} key={index} className="flex items-stretch cursor-pointer">
画面サイズに合わせてカラムの数変えるのが現実的ですかね

2023-11-17 12:31 UTC, kazu51-gh commented on src/components/book_list_view.tsx
> +              <div onClick={() => setSelectedBookIndex(index)} key={index} className="flex items-stretch cursor-pointer">
確かに...そっちの方向で調整しますか。

2023-11-17 12:37 UTC, Oni-Men commented on src/components/book_list_view.tsx
> +              <div onClick={() => setSelectedBookIndex(index)} key={index} className="flex items-stretch cursor-pointer">
`break-all`を付けると任意の場所で改行できるようになるみたい

```
<h3 className='font-semibold break-all text-ellipsis two-lines mb-2'>{book.name}</h3>
```
**break-allつけた状態**
![image](https://github.com/kazu51-gh/cac-library/assets/19502796/eae37f0d-b6c6-4ebb-ac4c-639b6a4b39c1)

2023-11-17 13:04 UTC, Oni-Men commented
レイアウト崩れ改善できたと思います。

2023-11-19 09:21 UTC, kazu51-gh commented
> レイアウト崩れ改善できたと思います。

2023-11-19 09:22 UTC, kazu51-gh commented
確認できました

2023-11-19 09:22 UTC, merged